import json
import glob
import os

data = []
for f in glob.glob('results/*_results.json'):
    with open(f, 'r') as fp:
        data.extend(json.load(fp))

# Sort by improvement ratio descending
data.sort(key=lambda x: x.get('improvement_ratio', 0), reverse=True)

with open('results/best_queries.md', 'w') as out:
    out.write('# Best SQL Optimizations (Before/After)\n\n')
    out.write('This document temporarily stores the exact SQL translations generated by the LLM-R2 engine that yielded significant speedups.\n\n')
    
    for q in data:
        ratio = q.get('improvement_ratio', 0)
        # Only show queries that actually improved
        if ratio > 1.1:
            out.write(f'## {q["query_name"]}\n')
            out.write(f'**Speedup:** {ratio:.2f}x\n')
            out.write(f'**Applied Rules:** {q.get("applied_rules", [])}\n\n')
            
            out.write('### Original SQL\n')
            out.write('```sql\n')
            out.write(f'{q["original_sql"]}\n')
            out.write('```\n\n')
            
            out.write('### Rewritten SQL\n')
            out.write('```sql\n')
            out.write(f'{q["rewritten_sql"]}\n')
            out.write('```\n\n')
            out.write('---\n\n')

print("Created results/best_queries.md")
